### ISSUE TITLE
Update diff dependency

### ISSUE THREAD

**Issue by ornic** [mvoss9000/unidiff#6]
```
diff  <3.5.0
Severity: high
Regular Expression Denial of Service (ReDoS) - https://github.com/advisories/GHSA-h6ch-v84p-w6p9
No fix available
node_modules/unidiff/node_modules/diff
  unidiff  *
  Depends on vulnerable versions of diff
  node_modules/unidiff
```

**Comment by fresheneesz** [comment]
Is this repo still maintained? This is still a problem almost a year later.

**Comment by mvoss9000** [comment]
OK - now it is : ).    I have been away quite some time. There were unnecessary packaging steps in the, ummm, package. Old diff dependency needed update to newer version. Should be good. **version 1.0.4** has been stripped down to the essential code and simplified file structure.
